services:
  - type: web
    name: lottery-backend
    env: node
    buildCommand: |
      cd backend && \
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && \
      apt-get update && \
      apt-get install -y chromium chromium-sandbox && \
      npm install && \
      mkdir -p /opt/render/.cache && \
      chmod -R 777 /opt/render/.cache
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
    buildFilter:
      paths:
      - backend/**/*