# render.yaml
services:
  - type: web
    name: lottery-backend
    runtime: node
    region: singapore
    plan: free
    
    buildCommand: npm install && npm run build --if-present
    
    startCommand: npm start
    
    # ...
    
    envVars:
      - key: NODE_ENV
        value: production
      # PUPPETEER_SKIP_CHROMIUM_DOWNLOAD has been removed
      - key: MONGODB_URI
        sync: false
      # ...